In [59]:
pip install Pillow

Note: you may need to restart the kernel to use updated packages.


In [60]:
from PIL import Image
import numpy as np

In [61]:
im = Image.open('sample.jpg') # Can be many different formats.
pix = im.load()
(x, y) =im.size  # Get the width and hight of the image for iterating over
print(x, y)
#print(pix[x,y])  # Get the RGBA Value of the a pixel of an image
#pix[x,y] = value  # Set the RGBA Value of the image (tuple)
#im.save('sample.png')  # Save the modified pixels as .png

600 800


In [62]:
pix_load = np.array(im.getdata()).reshape(im.size[0], im.size[1], 3)

In [63]:
pix_load

array([[[  4,   4,   4],
        [  3,   3,   3],
        [  3,   1,   2],
        ...,
        [ 52,   1,  10],
        [ 52,   0,   9],
        [ 53,   0,   8]],

       [[ 54,   1,   7],
        [ 52,   2,   5],
        [ 54,   4,   7],
        ...,
        [ 89,   2,  11],
        [ 88,   1,  10],
        [ 89,   2,  11]],

       [[ 87,   2,   9],
        [ 87,   2,   9],
        [ 87,   2,   9],
        ...,
        [  5,   4,   2],
        [  5,   4,   2],
        [  5,   4,   0]],

       ...,

       [[  4,   4,   2],
        [  4,   4,   2],
        [  5,   5,   3],
        ...,
        [133,  13,  25],
        [ 99,   8,  15],
        [ 55,   0,   0]],

       [[ 45,   1,   0],
        [ 43,   1,   3],
        [ 47,   0,   8],
        ...,
        [163,  99,  51],
        [173, 113,  59],
        [151,  96,  39]],

       [[165, 100,  42],
        [201, 144,  75],
        [178, 127,  35],
        ...,
        [ 96,   3,  13],
        [ 98,   2,  13],
        [ 97,   1,  12]]

In [64]:
new_img = pix_load.reshape((pix_load.shape[0]*pix_load.shape[1]), pix_load.shape[2])/255

In [65]:
new_img

array([[0.01568627, 0.01568627, 0.01568627],
       [0.01176471, 0.01176471, 0.01176471],
       [0.01176471, 0.00392157, 0.00784314],
       ...,
       [0.37647059, 0.01176471, 0.05098039],
       [0.38431373, 0.00784314, 0.05098039],
       [0.38039216, 0.00392157, 0.04705882]])

In [66]:
new_img.shape  # this picture has 2448 * 3264 pixel.  

#Every pixel has Red Green Blue from 0 - 255, which is normalized betwwen 0 - 1.

# Now we want to see which 16 centroids can be most representative.

(480000, 3)

In [92]:
from sklearn.cluster import KMeans

km = KMeans(
    n_clusters=16, init='random',
    n_init=10, max_iter=100, 
    tol=1e-04, random_state=0
)
y_km = km.fit_predict(new_img)

In [93]:
y_km

array([11, 11, 11, ..., 14, 14, 14], dtype=int32)

In [94]:
from scipy import stats
stats.describe(y_km)

DescribeResult(nobs=480000, minmax=(0, 15), mean=7.982566666666667, variance=34.53560552806706, skewness=-0.18931506407578727, kurtosis=-1.6001336645504047)

In [95]:
km.labels_

array([11, 11, 11, ..., 14, 14, 14], dtype=int32)

In [96]:
km.cluster_centers_

array([[0.20304776, 0.02018395, 0.03000184],
       [0.61684074, 0.03356097, 0.11740699],
       [0.26035668, 0.15271951, 0.06834303],
       [0.9304818 , 0.87378781, 0.64913219],
       [0.6381398 , 0.6102336 , 0.18550282],
       [0.52864699, 0.35082857, 0.19769366],
       [0.87349396, 0.79836242, 0.32674066],
       [0.76978696, 0.45207256, 0.27434671],
       [0.58266059, 0.46791643, 0.38644239],
       [0.97526363, 0.96911477, 0.93329724],
       [0.85964446, 0.01788084, 0.17084638],
       [0.09891639, 0.02515764, 0.01860784],
       [0.38846491, 0.26579584, 0.12482145],
       [0.74968017, 0.63902269, 0.55193004],
       [0.43596338, 0.02408685, 0.0726018 ],
       [0.30645557, 0.01849495, 0.04804441]])

In [97]:
centroids = np.round((km.cluster_centers_)*255)

In [98]:
centroids

array([[ 52.,   5.,   8.],
       [157.,   9.,  30.],
       [ 66.,  39.,  17.],
       [237., 223., 166.],
       [163., 156.,  47.],
       [135.,  89.,  50.],
       [223., 204.,  83.],
       [196., 115.,  70.],
       [149., 119.,  99.],
       [249., 247., 238.],
       [219.,   5.,  44.],
       [ 25.,   6.,   5.],
       [ 99.,  68.,  32.],
       [191., 163., 141.],
       [111.,   6.,  19.],
       [ 78.,   5.,  12.]])

In [103]:
list_ = []
for label_ in km.labels_:
    list_.append(centroids[label_])

In [104]:
list_

[array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),
 array([25.,  6.,  5.]),


In [ ]:
import numpy as np
import itertools
import scipy.misc as sc

img = np.zeros((305,314,3), dtype=np.uint8) 

with open ('coordinates') as coord, open('rgbvalues') as rgb:
    for coord,rgb in itertools.izip(coord,rgb):
        rgb = map(int, rgb.split(','))
        r = rgb

        coord = map(int, coord.split(','))
        c = coord
        img[c[0],c[1]] = [r[0],r[1],r[2]]
    img = sc.toimage(img)
    img.show()